__default__:
    submission_string: " "
    h_vmem:   1G
    tmem:   1G
    h_rt: 72:00:00
annotatate_delta:
    h_vmem:   24G
    tmem:   24G
    h_rt: 72:00:00
normalize_annotate:
    submission_string: " "
    h_vmem:   16G
    tmem:   16G
    h_rt: 72:00:00
majiq_build:
    submission_string: "-pe smp 4 -R y"
    h_vmem:   2G
    tmem:   2G
    h_rt: 72:00:00
squashed_normalize_annotate:
    submission_string: " "
    h_vmem:   32G
    tmem:   32G
    h_rt: 72:00:00
majiq_psi:
    h_vmem:   2G
    tmem:   2G
    h_rt: 72:00:00
    submission_string: "-pe smp 2 -R y"
majiq_single_psi:
    h_vmem:   2G
    tmem:   2G
    h_rt: 72:00:00
    submission_string: "-pe smp 2 -R y"
majiq_psi_tsv:
    h_vmem:   1G
    tmem:   1G
    submission_string: "-pe smp 4 -R y"
    h_rt: 72:00:00
majiq_delta_psi:
    h_vmem:   4G
    tmem:   4G
    h_rt: 72:00:00
    submission_string: "-pe smp 2 -R y"
majiq_delta_psi_tsv:
    h_vmem:   1G
    tmem:   1G
    h_rt: 72:00:00
    submission_string: "-pe smp 2 -R y"
majiq_annotate_junctions:
    h_vmem:   4G
    tmem:   4G
    h_rt: 72:00:00
majiq_psi_parse:
    h_vmem:   2G
    tmem:   2G
    h_rt: 72:00:00
star_tabs_to_beds:
    h_vmem:   1G
    tmem:   1G
    h_rt: 72:00:00
assembly:
    h_vmem:   2G
    tmem:   2G
    h_rt: 72:00:00
    submission_string: "-pe smp 4 -R y"
compose_merge:
    h_vmem:   1G
    tmem:   1G
    h_rt: 72:00:00
    submission_string: " "
compare_assemblies:
    h_vmem:   1G
    tmem:   1G
    h_rt: 72:00:00
    submission_string: " "
merge_assemblies:
    h_vmem:   1G
    tmem:   1G
    h_rt: 72:00:00
    submission_string: " "
diffexp:
    h_vmem:   1G
    tmem:   1G
    h_rt: 72:00:00
    submission_string: "-pe smp 8 -R y"
merge_scallop_gtfs:
    h_vmem:   1G
    tmem:   1G
    h_rt: 72:00:00
    submission_string: "-pe smp 2 -R y"
whippet_psi:
    h_vmem:   16G
    tmem:   16G
    h_rt: 72:00:00
