#always formated as so each comparison has an item called column_name. This MUST be called column_name. It has one item.
#then there are 2 more items, this should be named as you want the output to be named. Only two. The name must NEVER contain and UnderScore or you will have
#problems. I suggest camelCase names, but doesn't really matter as long as you can interpret them. Throughout the file they have to be unique.
#each of these two items has as many idenitifiers as you like, but they must be
#valid identifiers from the column_name column in the sample_csv. The first identifier is always the baseline group
compareControls:
  column_name:
    - group
  tdp43Positive:
    - positive
  tdp43Negative:
    - negative
